from . import hostel_bed
from . import hostel_building
from . import hostel_checkin
from . import hostel_contract
from . import hostel_occupancy_history
from . import hostel_room
from . import hostel_unit
from . import res_partner
from . import hostel_dashboard
from . import hostel_automation
from . import hostel_asset
from . import hostel_communication
from . import account_move
from . import hr_employee
from . import hostel_visitor
from . import hostel_student_attendance
from . import hostel_rent_invoice
from . import hostel_maintenance_request
from . import hostel_complaint
from . import hostel_mess
from . import hostel_laundry
from . import hostel_room_inspection
from . import hostel_announcement
from . import hostel_student_document
from . import hostel_settings
from . import hostel_report_wizard